# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hardware/zybo_z7_hdmi.xdc

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_processing_system7_0_0/main_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_processing_system7_0_0 || ORIG_REF_NAME==main_processing_system7_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_dynclk_0_0/main_axi_dynclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_dynclk_0_0 || ORIG_REF_NAME==main_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_vdma_0_0/main_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_vdma_0_0 || ORIG_REF_NAME==main_axi_vdma_0_0} -quiet] -quiet

# IP: bd/main/ip/main_v_tc_0_0/main_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_v_tc_0_0 || ORIG_REF_NAME==main_v_tc_0_0} -quiet] -quiet

# IP: bd/main/ip/main_v_axi4s_vid_out_0_0/main_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==main_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/main/ip/main_rgb2dvi_0_0/main_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_rgb2dvi_0_0 || ORIG_REF_NAME==main_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axis_subset_converter_0_0/main_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axis_subset_converter_0_0 || ORIG_REF_NAME==main_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/main/ip/main_xlconstant_0_0/main_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlconstant_0_0 || ORIG_REF_NAME==main_xlconstant_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_mem_intercon_0/main_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_mem_intercon_0 || ORIG_REF_NAME==main_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_smc_0/main_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_smc_0 || ORIG_REF_NAME==main_axi_smc_0} -quiet] -quiet

# IP: bd/main/ip/main_rst_ps7_0_100M_0/main_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_rst_ps7_0_100M_0 || ORIG_REF_NAME==main_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_mem_intercon_imp_xbar_0/main_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==main_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_mem_intercon_1/main_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_mem_intercon_1 || ORIG_REF_NAME==main_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/main/ip/main_axi_mem_intercon_imp_auto_pc_0/main_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==main_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_mem_intercon_imp_auto_ds_0/main_axi_mem_intercon_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_mem_intercon_imp_auto_ds_0 || ORIG_REF_NAME==main_axi_mem_intercon_imp_auto_ds_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_mem_intercon_imp_auto_pc_1/main_axi_mem_intercon_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_mem_intercon_imp_auto_pc_1 || ORIG_REF_NAME==main_axi_mem_intercon_imp_auto_pc_1} -quiet] -quiet

# XDC: /home/go/Desktop/ZyboZ7_10_Renderer/workspace_vivado/workspace_vivado.gen/sources_1/bd/main/main_ooc.xdc
