# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/go/Desktop/ZyboZ7_10_Renderer/workspace_vivado/workspace_vivado.srcs/sources_1/bd/main/ip/main_v_tc_0_0/main_v_tc_0_0.xci
# IP: The module: 'main_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/go/Desktop/ZyboZ7_10_Renderer/workspace_vivado/workspace_vivado.gen/sources_1/bd/main/ip/main_v_tc_0_0/main_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/go/Desktop/ZyboZ7_10_Renderer/workspace_vivado/workspace_vivado.gen/sources_1/bd/main/ip/main_v_tc_0_0/main_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/go/Desktop/ZyboZ7_10_Renderer/workspace_vivado/workspace_vivado.srcs/sources_1/bd/main/ip/main_v_tc_0_0/main_v_tc_0_0.xci
# IP: The module: 'main_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/go/Desktop/ZyboZ7_10_Renderer/workspace_vivado/workspace_vivado.gen/sources_1/bd/main/ip/main_v_tc_0_0/main_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/go/Desktop/ZyboZ7_10_Renderer/workspace_vivado/workspace_vivado.gen/sources_1/bd/main/ip/main_v_tc_0_0/main_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
